### PR TITLE
[WIP] New QML profiler

### PR DESCRIPTION
**Pull request by marques-bruno**
Getting the old c++-based profiler to work was trickier than thought, and even if I wouldn't have succeeded it would still be in a less readable form than a QML implementation, so I started reimplementing it in QML

### CODE REVIEW

**Comment by damienmarchal** [comment]
I will test that asap...you can merge when you think it is working

**Comment by marques-bruno** [comment]
> I will test that asap...you can merge when you think it is working

It works, but for now it's really a proto. and there's no treeView to see the subSteps.
You can test it still already.I never saw the old version working, so I'm only guessing what the features were according to what I'm reading in the code :(

**Comment by damienmarchal** [comment]
Still WIP.

**Comment by marques-bruno** [comment]
Yes I only merged because there was a commit for Bruno Carrez that inadvertently ended up in the pr... Still WIP

**Pull request merged**
