### PR TITLE
Improved DragNDrop in Hierarchy

### PR DESCRIPTION
**Pull request by marques-bruno**
Components can now be dropped between other components, and when dropped onto another one, links compatible fields.

### CODE REVIEW

**Comment by damienmarchal** [comment]
Nice...is this a WIP (really WIP)...or a WIP (to improve) ?

**Comment by marques-bruno** [comment]
WIP because it currently introduces an application crash kind of bug.. ;) I
don't want that in master as-is

**Comment by damienmarchal** [comment]
So can we try it in master-with-integration ?

**Comment by marques-bruno** [comment]
Yes, crashed are fixed. But dragndrop doesn't currently drop at the expected place (small error in insertion algorithm) I'll pr the fixes in a separate branch tomorrow

**Comment by marques-bruno** [comment]
Ready for merge

**Comment by marques-bruno** [comment]
This PR is getting a bit big... I shouldn't have pushed the fix for the new Prefab API in here...
But I think we should just merge it now :D

**Pull request merged**
